[project]
name = "kumano-shift-maker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django==6.0.2",
    "django-pandas>=0.6.7",
    "numpy>=2.4.2",
    "ortoolpy>=0.9.0",
    "pandas>=3.0.0",
    "pulp>=3.3.0",
]
